version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: watchlist
      POSTGRES_USER: lora
      POSTGRES_PASSWORD: Juemlochda2003!
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: Juemlochda2003!
    ports:
      - "5050:80"
    depends_on:
      - postgres
